name: Continues Delivery

on:
  push:
    branches: ["miRamita"]

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Descargando el proyecto
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Construir Imagen & push Docker image
        with:
          image: danieludea28/fundacion
          tags: v1, latest
          registry: registry-url.io
          dockerfile: Dockerfile.ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}